### ISSUE TITLE
Node stops randomly

### ISSUE THREAD

**Issue by LordMerlin** [bittorrent/go-btfs#304]
Good day.
This error is not the first time. The node just worked, and then the dashboard interface stops opening, you look in the logs and there it is. It happened that for many pages the log grew with a similar one.
WinServer 2008R2 system.

2023-03-28 18:27:08.673: goroutine 41267176 [running]:
2023-03-28 18:27:08.673: github.com/libp2p/go-libp2p-pnet.(*pskConn).Read(0x2d77f540, {0x1ac4eebc, 0x1, 0x1})
2023-03-28 18:27:08.673: 	pkg/mod/github.com/libp2p/go-libp2p-pnet@v0.2.0/psk_conn.go:43 +0x1b6
2023-03-28 18:27:08.673: github.com/multiformats/go-multistream.(*byteReader).ReadByte(0x2fab5608)
2023-03-28 18:27:08.673: 	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:460 +0x50
2023-03-28 18:27:08.673: github.com/multiformats/go-varint.ReadUvarint({0x29ba818, 0x2fab5608})
2023-03-28 18:27:08.673: 	pkg/mod/github.com/multiformats/go-varint@v0.0.6/varint.go:80 +0xa6
2023-03-28 18:27:08.673: github.com/multiformats/go-multistream.lpReadBuf({0x36b58100, 0x2d77f540})
2023-03-28 18:27:08.673: 	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:424 +0x9a
2023-03-28 18:27:08.673: github.com/multiformats/go-multistream.ReadNextTokenBytes({0x36b58100, 0x2d77f540})
2023-03-28 18:27:08.673: 	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:407 +0x2d
2023-03-28 18:27:08.673: github.com/multiformats/go-multistream.ReadNextToken(...)
2023-03-28 18:27:08.673: 	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:396
2023-03-28 18:27:08.673: github.com/multiformats/go-multistream.(*MultistreamMuxer).Negotiate(0x1612a600, {0x36b580e0, 0x2d77f540})
2023-03-28 18:27:08.674: 	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:310 +0xc3
2023-03-28 18:27:08.674: github.com/libp2p/go-conn-security-multistream.(*SSMuxer).selectProto.func1()
2023-03-28 18:27:08.674: 	pkg/mod/github.com/libp2p/go-conn-security-multistream@v0.2.0/ssms.go:66 +0xb2
2023-03-28 18:27:08.677: created by github.com/libp2p/go-conn-security-multistream.(*SSMuxer).selectProto
2023-03-28 18:27:08.677: 	pkg/mod/github.com/libp2p/go-conn-security-multistream@v0.2.0/ssms.go:63 +0x145

**Comment by LordMerlin** [comment]
Good afternoon.
A similar error occurs intermittently.
In case of occurrence next time, I will add here.

**Comment by LordMerlin** [comment]
Seichs looked at all his nodes. The other one also got an error. The node does not work accordingly. Dashboard won't open.
Version 2,3,0, now I will update to 2,3,1

2023-03-26 23:16:56.774: panic: runtime error: slice bounds out of range [:24] with capacity 1
2023-03-26 23:16:56.867: 
2023-03-26 23:16:56.867: goroutine 4846119341 [running]:
2023-03-26 23:16:56.867: github.com/libp2p/go-libp2p-pnet.(*pskConn).Read(0xc0d814b640, {0xc102e4372a, 0x1?, 0x1})
2023-03-26 23:16:56.867: 	pkg/mod/github.com/libp2p/go-libp2p-pnet@v0.2.0/psk_conn.go:43 +0x185
2023-03-26 23:16:56.867: github.com/multiformats/go-multistream.(*byteReader).ReadByte(0xc107f9faa0)
2023-03-26 23:16:56.867: 	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:460 +0x4e
2023-03-26 23:16:56.913: github.com/multiformats/go-varint.ReadUvarint({0x362e4c0, 0xc107f9faa0})
2023-03-26 23:16:56.913: 	pkg/mod/github.com/multiformats/go-varint@v0.0.6/varint.go:80 +0x74
2023-03-26 23:16:56.913: github.com/multiformats/go-multistream.lpReadBuf({0x1b7ee49e5b8?, 0xc0d814b640})
2023-03-26 23:16:56.913: 	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:424 +0x94
2023-03-26 23:16:56.913: github.com/multiformats/go-multistream.ReadNextTokenBytes({0x1b7ee49e5b8?, 0xc0d814b640?})
2023-03-26 23:16:56.913: 	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:407 +0x27
2023-03-26 23:16:56.913: github.com/multiformats/go-multistream.ReadNextToken(...)
2023-03-26 23:16:56.913: 	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:396
2023-03-26 23:16:56.913: github.com/multiformats/go-multistream.(*MultistreamMuxer).Negotiate(0x365be08?, {0x1b7ee49e588?, 0xc0d814b640})
2023-03-26 23:16:56.913: 	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:310 +0xde
2023-03-26 23:16:56.953: github.com/libp2p/go-conn-security-multistream.(*SSMuxer).selectProto.func1()
2023-03-26 23:16:56.953: 	pkg/mod/github.com/libp2p/go-conn-security-multistream@v0.2.0/ssms.go:66 +0xaf
2023-03-26 23:16:57.030: created by github.com/libp2p/go-conn-security-multistream.(*SSMuxer).selectProto
2023-03-26 23:16:57.053: 	pkg/mod/github.com/libp2p/go-conn-security-multistream@v0.2.0/ssms.go:63 +0x15c

**Comment by Richard2GitHub** [comment]
Hi, LordMerlin. After upgrading to v2.3.1, does this 'runtime error' issue persist?

**Comment by Richard2GitHub** [comment]
Due to the lack of response, this issue will be closed for now. If you have any further questions or concerns, please don't hesitate to reopen the issue or create a new one. Thank you for your understanding.
